create extension if not exists pgcrypto;

do $$ begin create type dog_status as enum ('AVAILABLE','RESERVED','SOLD','ARCHIVED'); exception when duplicate_object then null; end $$;
do $$ begin create type lead_status as enum ('NEW','CONTACTED','VIDEO','VISIT','RESERVATION','PURCHASE','NOT_CURRENT'); exception when duplicate_object then null; end $$;
do $$ begin create type mating_status as enum ('MATED','PREGNANCY_CHECK','PREGNANT','NOT_PREGNANT','DUE','BIRTHED','FAILED'); exception when duplicate_object then null; end $$;

create table if not exists dogs(
 id uuid primary key default gen_random_uuid(), name text not null, breed text, sex text, birth_date date,
 chip_number text unique, status dog_status not null default 'AVAILABLE', price numeric(12,2),
 is_adult boolean not null default false, is_female boolean not null default false, is_male boolean not null default false,
 color text, size text, weight numeric(8,2), mother_id uuid references dogs(id), father_id uuid references dogs(id),
 litter_id uuid, notes text, archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists buyers(id uuid primary key default gen_random_uuid(),name text not null,phone text,email text,address text,notes text,created_at timestamptz default now());
create table if not exists leads(id uuid primary key default gen_random_uuid(),name text not null,phone text,email text,whatsapp text,viber text,breed_interest text,dog_id uuid references dogs(id),interest_date date default current_date,status lead_status not null default 'NEW',notes text,created_at timestamptz default now());
create table if not exists heat_cycles(id uuid primary key default gen_random_uuid(),female_id uuid not null references dogs(id),start_date date not null,end_date date,duration_days int,successful_mating boolean default false,next_estimated_date date,notes text,created_at timestamptz default now());
create table if not exists matings(id uuid primary key default gen_random_uuid(),female_id uuid not null references dogs(id),male_id uuid not null references dogs(id),heat_cycle_id uuid references heat_cycles(id),mating_date date not null,mating_dates date[] default '{}',pregnancy_confirmed boolean default false,pregnancy_check_date date,pregnancy_notes text,estimated_due_date date,actual_birth_date date,puppy_count int,litter_id uuid,status mating_status not null default 'MATED',notes text,created_at timestamptz default now());
create table if not exists pregnancies(id uuid primary key default gen_random_uuid(),female_id uuid not null references dogs(id),male_id uuid references dogs(id),mating_id uuid references matings(id),confirmed boolean default false,check_date date,result text,veterinary_notes text,estimated_due_date date,actual_birth_date date,puppy_count int,status text,created_at timestamptz default now());
create table if not exists litters(id uuid primary key default gen_random_uuid(),name text not null,mother_id uuid references dogs(id),father_id uuid references dogs(id),mating_id uuid references matings(id),birth_date date,expected_birth_date date,born_count int,alive_count int,notes text,archived_at timestamptz,created_at timestamptz default now());
DO $$ BEGIN ALTER TABLE dogs ADD CONSTRAINT dogs_litter_fk FOREIGN KEY(litter_id) REFERENCES litters(id); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
create table if not exists vaccinations(id uuid primary key default gen_random_uuid(),dog_id uuid not null references dogs(id) on delete restrict,name text not null,vaccination_date date not null,next_date date,veterinarian text,notes text,document_path text,created_at timestamptz default now());
create table if not exists dewormings(id uuid primary key default gen_random_uuid(),dog_id uuid not null references dogs(id) on delete restrict,date date not null,product text,dose text,weight numeric(8,2),next_date date,notes text,document_path text,created_at timestamptz default now());
create table if not exists health_records(id uuid primary key default gen_random_uuid(),dog_id uuid not null references dogs(id) on delete restrict,event_date date not null,event_type text not null,description text,notes text,document_path text,created_at timestamptz default now());
create table if not exists sales(id uuid primary key default gen_random_uuid(),dog_id uuid not null unique references dogs(id) on delete restrict,buyer_id uuid references buyers(id),sale_price numeric(12,2) not null,sale_date date,notes text,created_at timestamptz default now());
create table if not exists payments(id uuid primary key default gen_random_uuid(),dog_id uuid not null references dogs(id) on delete restrict,kind text not null check(kind in ('DEPOSIT','PAYMENT')),amount numeric(12,2) not null check(amount>=0),payment_date date not null default current_date,notes text,created_at timestamptz default now());
create table if not exists expenses(id uuid primary key default gen_random_uuid(),amount numeric(12,2) not null check(amount>=0),expense_date date not null default current_date,category text,notes text,created_at timestamptz default now());
create table if not exists kennels(id int primary key check(id between 1 and 6),name text not null unique,current_state text,notes text,photo_path text);
insert into kennels(id,name) values(1,'Kennel 1'),(2,'Kennel 2'),(3,'Kennel 3'),(4,'Kennel 4'),(5,'Kennel 5'),(6,'Kennel 6') on conflict(id) do update set name=excluded.name;
create table if not exists kennel_assignments(id uuid primary key default gen_random_uuid(),kennel_id int not null references kennels(id),dog_id uuid not null references dogs(id),start_date date not null default current_date,end_date date,notes text,created_at timestamptz default now());
create table if not exists kennel_daily_tasks(id uuid primary key default gen_random_uuid(),kennel_id int not null references kennels(id),task_date date not null,task_key text not null,completed boolean not null default false,notes text,unique(kennel_id,task_date,task_key));
create table if not exists handover_checklists(id uuid primary key default gen_random_uuid(),dog_id uuid not null unique references dogs(id),handover_date date,recipient text,notes text,created_at timestamptz default now());
create table if not exists handover_tasks(id uuid primary key default gen_random_uuid(),checklist_id uuid not null references handover_checklists(id) on delete cascade,task_key text not null,completed boolean not null default false,unique(checklist_id,task_key));
create table if not exists documents(id uuid primary key default gen_random_uuid(),dog_id uuid references dogs(id) on delete restrict,litter_id uuid references litters(id) on delete restrict,name text not null,path text not null,mime_type text,created_at timestamptz default now());
create table if not exists photos(id uuid primary key default gen_random_uuid(),dog_id uuid not null references dogs(id) on delete restrict,path text not null,is_primary boolean default false,created_at timestamptz default now());
create table if not exists videos(id uuid primary key default gen_random_uuid(),dog_id uuid not null references dogs(id) on delete restrict,path text not null,created_at timestamptz default now());
create table if not exists calendar_events(id uuid primary key default gen_random_uuid(),event_date date not null,title text not null,event_type text not null,dog_id uuid references dogs(id),kennel_id int references kennels(id),notes text,created_at timestamptz default now());

create unique index if not exists uq_active_dog_kennel on kennel_assignments(dog_id) where end_date is null;
create index if not exists idx_dogs_status on dogs(status); create index if not exists idx_dogs_litter on dogs(litter_id); create index if not exists idx_dogs_mother on dogs(mother_id); create index if not exists idx_dogs_father on dogs(father_id);
create index if not exists idx_payments_dog on payments(dog_id); create index if not exists idx_payments_date on payments(payment_date); create index if not exists idx_expenses_date on expenses(expense_date);
create index if not exists idx_heat_female on heat_cycles(female_id); create index if not exists idx_mating_female on matings(female_id); create index if not exists idx_pregnancy_female on pregnancies(female_id);
create index if not exists idx_kennel_tasks on kennel_daily_tasks(kennel_id,task_date); create index if not exists idx_kennel_assignments on kennel_assignments(kennel_id,start_date,end_date);

create or replace function set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
drop trigger if exists dogs_updated_at on dogs; create trigger dogs_updated_at before update on dogs for each row execute function set_updated_at();
create or replace function calculate_heat_duration() returns trigger language plpgsql as $$ begin if new.start_date is not null and new.end_date is not null then new.duration_days=(new.end_date-new.start_date)+1; end if; return new; end $$;
drop trigger if exists heat_duration on heat_cycles; create trigger heat_duration before insert or update on heat_cycles for each row execute function calculate_heat_duration();
create or replace function calculate_due_date() returns trigger language plpgsql as $$ begin if new.estimated_due_date is null and new.mating_date is not null then new.estimated_due_date=new.mating_date+63; end if; return new; end $$;
drop trigger if exists mating_due_date on matings; create trigger mating_due_date before insert or update on matings for each row execute function calculate_due_date();

alter table dogs enable row level security; alter table buyers enable row level security; alter table leads enable row level security; alter table heat_cycles enable row level security; alter table matings enable row level security; alter table pregnancies enable row level security; alter table litters enable row level security; alter table vaccinations enable row level security; alter table dewormings enable row level security; alter table health_records enable row level security; alter table sales enable row level security; alter table payments enable row level security; alter table expenses enable row level security; alter table kennels enable row level security; alter table kennel_assignments enable row level security; alter table kennel_daily_tasks enable row level security; alter table handover_checklists enable row level security; alter table handover_tasks enable row level security; alter table documents enable row level security; alter table photos enable row level security; alter table videos enable row level security; alter table calendar_events enable row level security;

do $$ declare t text; begin foreach t in array array['dogs','buyers','leads','heat_cycles','matings','pregnancies','litters','vaccinations','dewormings','health_records','sales','payments','expenses','kennels','kennel_assignments','kennel_daily_tasks','handover_checklists','handover_tasks','documents','photos','videos','calendar_events'] loop execute format('drop policy if exists admin_all on %I',t); execute format('create policy admin_all on %I for all to authenticated using (auth.uid() is not null) with check (auth.uid() is not null)',t); end loop; end $$;

insert into storage.buckets(id,name,public) values('private-media','private-media',false) on conflict(id) do nothing;
drop policy if exists "private media authenticated" on storage.objects;
create policy "private media authenticated" on storage.objects for all to authenticated using(bucket_id='private-media' and auth.uid() is not null) with check(bucket_id='private-media' and auth.uid() is not null);
