'use client';
import {useEffect,useState} from 'react';import {supabase} from '@/lib/supabase';import DogSelect from '@/components/DogSelect';
export default function Finance(){const[p,setP]=useState<any[]>([]),[e,setE]=useState<any[]>([]),[form,setForm]=useState<any>({kind:'DEPOSIT',payment_date:new Date().toISOString().slice(0,10)}),[edit,setEdit]=useState<any>(null),[msg,setMsg]=useState('');
 const load=async()=>{const s=supabase();const[a,b]=await Promise.all([s.from('payments').select('*').order('payment_date',{ascending:false}),s.from('expenses').select('*').order('expense_date',{ascending:false})]);setP(a.data||[]);setE(b.data||[])};useEffect(()=>{load()},[]);
 const income=p.reduce((x,y)=>x+Number(y.amount||0),0),expense=e.reduce((x,y)=>x+Number(y.amount||0),0);
 async function save(ev:React.FormEvent){ev.preventDefault();const payload={...form,amount:Number(form.amount)};const r=edit?await supabase().from('payments').update(payload).eq('id',edit.id):await supabase().from('payments').insert(payload);if(r.error)setMsg(r.error.message);else{setMsg('Sikeres mentés.');setForm({kind:'DEPOSIT',payment_date:new Date().toISOString().slice(0,10)});setEdit(null);load()}}
 async function remove(id:string){if(!confirm('Törlöd a befizetést?'))return;await supabase().from('payments').delete().eq('id',id);load()}
 return <><div className="title">Pénzügyek</div><div className="grid" style={{marginTop:15}}><div className="card"><div className="muted">Összes bevétel</div><div className="value">{income.toLocaleString('hu-HU')} Ft</div></div><div className="card"><div className="muted">Összes kiadás</div><div className="value">{expense.toLocaleString('hu-HU')} Ft</div></div><div className="card"><div className="muted">Egyenleg</div><div className="value">{(income-expense).toLocaleString('hu-HU')} Ft</div></div></div><br/>
 <div className="card"><h2>{edit?'Befizetés módosítása':'Új befizetés'}</h2><form className="form" onSubmit={save}><label>Kutya<DogSelect value={form.dog_id||''} onChange={v=>setForm({...form,dog_id:v})}/></label><label>Típus<select className="select" value={form.kind} onChange={x=>setForm({...form,kind:x.target.value})}><option value="DEPOSIT">Foglaló</option><option value="PAYMENT">További befizetés</option></select></label><label>Összeg<input className="input" type="number" min="0" required value={form.amount||''} onChange={x=>setForm({...form,amount:x.target.value})}/></label><label>Dátum<input className="input" type="date" required value={form.payment_date} onChange={x=>setForm({...form,payment_date:x.target.value})}/></label><label className="full">Megjegyzés<textarea className="textarea" value={form.notes||''} onChange={x=>setForm({...form,notes:x.target.value})}/></label><div className="full"><button className="btn">Mentés</button>{edit&&<button type="button" className="btn secondary" style={{marginLeft:8}} onClick={()=>{setEdit(null);setForm({kind:'DEPOSIT',payment_date:new Date().toISOString().slice(0,10)})}}>Mégse</button>}<span className="muted" style={{marginLeft:10}}>{msg}</span></div></form></div><br/>
 <div className="tablewrap"><table className="table"><thead><tr><th>Dátum</th><th>Kutya</th><th>Típus</th><th>Összeg</th><th>Művelet</th></tr></thead><tbody>{p.map(x=><tr key={x.id}><td>{x.payment_date}</td><td>{x.dog_id}</td><td>{x.kind==='DEPOSIT'?'Foglaló':'További befizetés'}</td><td>{Number(x.amount).toLocaleString('hu-HU')} Ft</td><td><button className="btn secondary" onClick={()=>{setEdit(x);setForm(x)}}>Módosítás</button><button className="btn danger" style={{marginLeft:6}} onClick={()=>remove(x.id)}>Törlés</button></td></tr>)}</tbody></table></div></>}
