'use client';
import {useEffect,useState} from 'react';import {supabase} from '@/lib/supabase';import DogSelect from '@/components/DogSelect';
const tasks=[['cleaning','Takarítás'],['disinfection','Fertőtlenítés'],['bedding','Forgács / alom cseréje'],['feeding','Etetés'],['watering','Itatás'],['dog_check','Kutyák ellenőrzése'],['bowls','Tálak tisztítása'],['other','Egyéb']];
export default function Kennels(){const[day,setDay]=useState(new Date().toISOString().slice(0,10)),[k,setK]=useState(1),[state,setState]=useState<Record<string,boolean>>({}),[assigned,setAssigned]=useState<any[]>([]),[dog,setDog]=useState(''),[note,setNote]=useState(''),[msg,setMsg]=useState('');
 const load=async()=>{const s=supabase();const t=await s.from('kennel_daily_tasks').select('*').eq('kennel_id',k).eq('task_date',day);setState(Object.fromEntries((t.data||[]).map(x=>[x.task_key,x.completed])));const a=await s.from('kennel_assignments').select('id,dog_id,start_date,end_date,notes,dogs(name,breed)').eq('kennel_id',k).is('end_date',null);setAssigned(a.data||[])};useEffect(()=>{load()},[day,k]);
 async function toggle(key:string){const v=!state[key];const r=await supabase().from('kennel_daily_tasks').upsert({kennel_id:k,task_date:day,task_key:key,completed:v},{onConflict:'kennel_id,task_date,task_key'});if(!r.error)setState(x=>({...x,[key]:v}));}
 async function assign(){if(!dog)return;const existing=await supabase().from('kennel_assignments').select('id').eq('dog_id',dog).is('end_date',null).maybeSingle();if(existing.data){setMsg('Ez a kutya már egy másik kennelhez van rendelve.');return}const r=await supabase().from('kennel_assignments').insert({kennel_id:k,dog_id:dog,start_date:day,notes:note||null});if(r.error)setMsg(r.error.message);else{setMsg('Kutya hozzárendelve.');setDog('');setNote('');load()}}
 async function unassign(id:string){await supabase().from('kennel_assignments').update({end_date:day}).eq('id',id);load()}
 const done=tasks.filter(([key])=>state[key]).length;
 return <><div className="top"><div><div className="title">Kennelkezelés</div><div className="muted">Pontosan 6 kennel. A napi checklist kennel + dátum szerint külön rekord.</div></div></div><div className="toolbar"><select className="select" value={k} onChange={e=>setK(Number(e.target.value))}>{[1,2,3,4,5,6].map(x=><option key={x} value={x}>Kennel {x}</option>)}</select><input className="input" type="date" value={day} onChange={e=>setDay(e.target.value)}/></div>
 <div className="grid"><div className="card"><h2>Kennel {k} – napi checklist</h2><div className="muted">Kész: {done}/{tasks.length} ({Math.round(done/tasks.length*100)}%)</div>{tasks.map(([key,label])=><label key={key} style={{display:'flex',gap:12,alignItems:'center',padding:'13px 0',borderBottom:'1px solid #eee',fontSize:16}}><input style={{width:22,height:22}} type="checkbox" checked={!!state[key]} onChange={()=>toggle(key)}/>{label}</label>)}</div>
 <div className="card"><h2>Kutyák a kennelben</h2>{assigned.length?assigned.map(a=><div key={a.id} style={{padding:'10px 0',borderBottom:'1px solid #eee'}}><strong>{a.dogs?.name||a.dog_id}</strong><div className="muted">{a.dogs?.breed||''} · kezdés: {a.start_date}</div><button className="btn secondary" style={{marginTop:6}} onClick={()=>unassign(a.id)}>Kivétel / lezárás</button></div>):<p className="muted">Nincs aktív hozzárendelés.</p>}<h3>Új hozzárendelés</h3><DogSelect value={dog} onChange={setDog}/><input className="input" style={{marginTop:8,width:'100%'}} placeholder="Megjegyzés" value={note} onChange={e=>setNote(e.target.value)}/><button className="btn" style={{marginTop:8}} onClick={assign}>Hozzárendelés</button>{msg&&<p className="muted">{msg}</p>}</div></div></>}
