'use client';
import {useEffect,useState} from 'react';import Link from 'next/link';import {supabase} from '@/lib/supabase';
const cards=[['Kölyökkutyák','puppies'],['Elérhető','available'],['Foglalt','reserved'],['Eladott','sold'],['Felnőtt','adult'],['Anya kutyák','female'],['Kan kutyák','male'],['Aktív almok','litters'],['Vemhes','pregnant']];
export default function Dashboard(){const[d,setD]=useState<Record<string,string>>({}),[tasks,setTasks]=useState<any[]>([]);
 useEffect(()=>{(async()=>{const s=supabase();const q=async(filter?:any)=>{let x=s.from('dogs').select('*',{count:'exact',head:true});if(filter)x=x.match(filter);const r=await x;return r.count||0};const [puppies,available,reserved,sold,adult,female,male,litters,pregnant]=await Promise.all([q({is_adult:false}),q({status:'AVAILABLE'}),q({status:'RESERVED'}),q({status:'SOLD'}),q({is_adult:true}),q({is_female:true,is_adult:true}),q({is_male:true,is_adult:true}),s.from('litters').select('*',{count:'exact',head:true}).then(r=>r.count||0),s.from('pregnancies').select('*',{count:'exact',head:true}).eq('status','PREGNANT').then(r=>r.count||0)]);const pays=await s.from('payments').select('amount'),ex=await s.from('expenses').select('amount');const income=(pays.data||[]).reduce((a,x)=>a+Number(x.amount||0),0),expense=(ex.data||[]).reduce((a,x)=>a+Number(x.amount||0),0);setD({puppies:String(puppies),available:String(available),reserved:String(reserved),sold:String(sold),adult:String(adult),female:String(female),male:String(male),litters:String(litters),pregnant:String(pregnant),income:income.toLocaleString('hu-HU')+' Ft',expense:expense.toLocaleString('hu-HU')+' Ft',balance:(income-expense).toLocaleString('hu-HU')+' Ft'});
 const today=new Date().toISOString().slice(0,10),future=new Date(Date.now()+14*86400000).toISOString().slice(0,10);const [v,w,c]=await Promise.all([s.from('vaccinations').select('id,dog_id,next_date,name').gte('next_date',today).lte('next_date',future).order('next_date'),s.from('dewormings').select('id,dog_id,next_date,product').gte('next_date',today).lte('next_date',future).order('next_date'),s.from('matings').select('id,female_id,estimated_due_date,status').gte('estimated_due_date',today).lte('estimated_due_date',future).order('estimated_due_date')]);setTasks([...((v.data||[]).map(x=>({...x,type:'Oltás'}))),...((w.data||[]).map(x=>({...x,type:'Féreghajtás'}))),...((c.data||[]).map(x=>({...x,type:'Várható ellés'})))].slice(0,12));})();},[]);
 return <><div className="top"><div><div className="title">Dashboard</div><div className="muted">Központi tenyésztési, kennel- és pénzügyi áttekintés</div></div></div><div className="grid">{cards.map(([a,b])=><div className="card" key={b}><div className="muted">{a}</div><div className="value">{d[b]??'…'}</div></div>)}<div className="card"><div className="muted">Bevétel</div><div className="value">{d.income||'…'}</div></div><div className="card"><div className="muted">Kiadás</div><div className="value">{d.expense||'…'}</div></div><div className="card"><div className="muted">Egyenleg</div><div className="value">{d.balance||'…'}</div></div></div>
 <div className="card" style={{marginTop:16}}><h2>Mai / következő teendők</h2>{tasks.length?<div>{tasks.map(x=><div key={`${x.type}-${x.id}`} style={{padding:'10px 0',borderBottom:'1px solid #eee'}}><strong>{x.type}</strong> · {x.next_date||x.estimated_due_date}<div className="muted">Kutya ID: {x.dog_id||x.female_id}</div></div>)}</div>:<p className="muted">A következő 14 napra nincs rögzített oltás-, féreghajtás- vagy ellési esemény.</p>}</div>
 <div className="toolbar"><Link className="btn" href="/admin/dogs">Kutyák kezelése</Link><Link className="btn secondary" href="/admin/kennels">Kennel checklist</Link><Link className="btn secondary" href="/admin/finance">Pénzügyek</Link><Link className="btn secondary" href="/admin/handover">Átadási checklist</Link></div></>}
