'use client';
import {useEffect,useState} from 'react';import {supabase} from '@/lib/supabase';import DogSelect from '@/components/DogSelect';
const tasks=[['bath','Fürdetés'],['brush','Fésülés'],['vaccination_book','Oltási könyv összekészítése'],['starter_food','Kezdő táp csomag összekészítése'],['contract','Adásvételi szerződés elkészítése'],['chip','Chip ellenőrzése'],['vaccines','Oltások ellenőrzése'],['deworming','Féreghajtás ellenőrzése'],['documents','Dokumentumok ellenőrzése']];
export default function Page(){const[id,setId]=useState(''),[cid,setCid]=useState(''),[state,setState]=useState<Record<string,boolean>>({}),[meta,setMeta]=useState<any>({}),[msg,setMsg]=useState('');
 async function load(){if(!id)return;const s=supabase();let c=await s.from('handover_checklists').select('*').eq('dog_id',id).maybeSingle();if(!c.data){setCid('');setState({});return}setCid(c.data.id);setMeta(c.data);const t=await s.from('handover_tasks').select('*').eq('checklist_id',c.data.id);setState(Object.fromEntries((t.data||[]).map(x=>[x.task_key,x.completed])))}
 async function ensure(){if(!id)return;let c=await supabase().from('handover_checklists').select('*').eq('dog_id',id).maybeSingle();if(!c.data)c=await supabase().from('handover_checklists').insert({dog_id:id}).select().single();if(c.data){for(const [key] of tasks)await supabase().from('handover_tasks').upsert({checklist_id:c.data.id,task_key:key,completed:false},{onConflict:'checklist_id,task_key'});await load();}}
 const done=tasks.filter(([k])=>state[k]).length,percent=Math.round(done/tasks.length*100);
 async function saveMeta(){if(!cid)return;const r=await supabase().from('handover_checklists').update({handover_date:meta.handover_date||null,recipient:meta.recipient||null,notes:meta.notes||null}).eq('id',cid);setMsg(r.error?.message||'Átadási adatok mentve.')}
 return <><div className="title">Kölyökkutya átadási checklist</div><div className="card" style={{marginTop:15}}><div className="form"><label>Kutya<DogSelect value={id} onChange={v=>{setId(v);setCid('')}}/></label><div style={{alignSelf:'end'}}><button className="btn secondary" type="button" onClick={ensure}>Checklist megnyitása / létrehozása</button></div></div>{cid&&<><hr/><h3>Készültség: {percent}% {percent===100?'– Átadásra kész':''}</h3>{tasks.map(([key,label])=><label key={key} style={{display:'flex',gap:12,alignItems:'center',padding:12,borderBottom:'1px solid #eee',fontSize:16}}><input style={{width:22,height:22}} type="checkbox" checked={!!state[key]} onChange={async e=>{const v=e.target.checked;await supabase().from('handover_tasks').update({completed:v}).eq('checklist_id',cid).eq('task_key',key);setState(x=>({...x,[key]:v}))}}/>{label}</label>)}<div className="form" style={{marginTop:15}}><label>Átadás dátuma<input className="input" type="date" value={meta.handover_date||''} onChange={e=>setMeta({...meta,handover_date:e.target.value})}/></label><label>Átvevő<input className="input" value={meta.recipient||''} onChange={e=>setMeta({...meta,recipient:e.target.value})}/></label><label className="full">Megjegyzés<textarea className="textarea" value={meta.notes||''} onChange={e=>setMeta({...meta,notes:e.target.value})}/></label><button className="btn full" onClick={saveMeta}>Átadási adatok mentése</button></div>{msg&&<p className="success">{msg}</p>}</>}</div></>}
