'use client';
import {useEffect,useMemo,useState} from 'react';
import {supabase} from '@/lib/supabase';
import MediaManager from '@/components/MediaManager';

const labels:any={AVAILABLE:'Elérhető',RESERVED:'Foglalt',SOLD:'Eladva',ARCHIVED:'Archív'};
export default function Dogs(){
 const [data,setData]=useState<any[]>([]),[form,setForm]=useState<any>({status:'AVAILABLE',is_adult:false,is_female:false,is_male:false}),[edit,setEdit]=useState<any>(null),[search,setSearch]=useState(''),[msg,setMsg]=useState(''),[filter,setFilter]=useState('ALL'),[adult,setAdult]=useState('ALL'),[selected,setSelected]=useState<string>('');
 const load=async()=>{let q=supabase().from('dogs').select('*').order('created_at',{ascending:false});if(search){const s=search.replace(/[%(),]/g,' ');q=q.or(`name.ilike.%${s}%,chip_number.ilike.%${s}%,breed.ilike.%${s}%`)}if(filter!=='ALL')q=q.eq('status',filter);if(adult!=='ALL')q=q.eq('is_adult',adult==='true');const r=await q;if(r.error)setMsg(r.error.message);else setData(r.data||[])};
 useEffect(()=>{const p=new URLSearchParams(location.search);if(p.get('status'))setFilter(p.get('status')!);if(p.get('adult'))setAdult(p.get('adult')!);},[]);useEffect(()=>{load()},[search,filter,adult]);
 async function save(e:React.FormEvent){e.preventDefault();setMsg('');const payload={...form,price:form.price===''?null:Number(form.price)||null,weight:form.weight===''?null:Number(form.weight)||null};const r=edit?await supabase().from('dogs').update(payload).eq('id',edit.id):await supabase().from('dogs').insert(payload);if(r.error)setMsg(r.error.message);else{setMsg('Sikeres mentés.');setForm({status:'AVAILABLE',is_adult:false,is_female:false,is_male:false});setEdit(null);await load()}}
 async function archive(id:string){if(!confirm('A kutya rekordját archiválod? Az adatok megmaradnak.'))return;const r=await supabase().from('dogs').update({status:'ARCHIVED',archived_at:new Date().toISOString()}).eq('id',id);if(r.error)setMsg(r.error.message);else load()}
 const weeks=(birth:string)=>birth?Math.max(0,Math.floor((Date.now()-new Date(birth+'T00:00:00').getTime())/604800000)):null;
 return <>
 <div className="top"><div><div className="title">Kutyák</div><div className="muted">Egy kutya mindig egyetlen központi rekord. A státuszváltás nem készít másolatot.</div></div></div>
 <div className="toolbar"><input className="input" placeholder="Keresés név, chip, fajta…" value={search} onChange={e=>setSearch(e.target.value)}/><button className="btn secondary" type="button" onClick={()=>{const rows=[['Név','Fajta','Születés','Chip','Státusz','Ár'],...data.map(x=>[x.name,x.breed||'',x.birth_date||'',x.chip_number||'',labels[x.status]||x.status,x.price||''])];const csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('\"','\"\"')}"`).join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='kutyak.csv';a.click();URL.revokeObjectURL(a.href)}}}>CSV export</button><select className="select" value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">Minden státusz</option><option value="AVAILABLE">Elérhető</option><option value="RESERVED">Foglalt</option><option value="SOLD">Eladva</option><option value="ARCHIVED">Archív</option></select><select className="select" value={adult} onChange={e=>setAdult(e.target.value)}><option value="ALL">Minden életkor</option><option value="false">Kölyök</option><option value="true">Felnőtt</option></select></div>
 <div className="card"><form className="form" onSubmit={save}>
 {['name','breed','sex','birth_date','chip_number','color','size','price','weight'].map(k=><label key={k}>{({name:'Név',breed:'Fajta',sex:'Nem',birth_date:'Születési dátum',chip_number:'Chip',color:'Szín',size:'Méret',price:'Ár (Ft)',weight:'Súly (kg)'} as any)[k]}<input className="input" type={k==='birth_date'?'date':k==='price'||k==='weight'?'number':'text'} required={k==='name'} value={form[k]??''} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}
 <label>Státusz<select className="select" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="AVAILABLE">Elérhető</option><option value="RESERVED">Foglalt</option><option value="SOLD">Eladva</option><option value="ARCHIVED">Archív</option></select></label>
 <label>Felnőtt <input type="checkbox" checked={!!form.is_adult} onChange={e=>setForm({...form,is_adult:e.target.checked})}/></label><label>Szuka <input type="checkbox" checked={!!form.is_female} onChange={e=>setForm({...form,is_female:e.target.checked,is_male:false})}/></label><label>Kan <input type="checkbox" checked={!!form.is_male} onChange={e=>setForm({...form,is_male:e.target.checked,is_female:false})}/></label>
 <label className="full">Megjegyzés<textarea className="textarea" value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></label><div className="full"><button className="btn">{edit?'Módosítás mentése':'Kutya mentése'}</button>{edit&&<button type="button" className="btn secondary" style={{marginLeft:8}} onClick={()=>{setEdit(null);setForm({status:'AVAILABLE',is_adult:false,is_female:false,is_male:false})}}>Mégse</button>} {msg&&<span className={msg.includes('Siker')?'success':'error'} style={{marginLeft:10}}>{msg}</span>}</div></form></div>
 <br/><div className="tablewrap"><table className="table"><thead><tr><th>Név</th><th>Fajta</th><th>Kor</th><th>Chip</th><th>Státusz</th><th>Ár</th><th>Műveletek</th></tr></thead><tbody>{data.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.breed||''}</td><td>{weeks(x.birth_date)!=null?`${weeks(x.birth_date)} hetes`:''}</td><td>{x.chip_number||''}</td><td><span className="badge">{labels[x.status]||x.status}</span></td><td>{x.price?Number(x.price).toLocaleString('hu-HU')+' Ft':''}</td><td><button className="btn secondary" onClick={()=>{setEdit(x);setForm(x)}}>Szerkesztés</button><button className="btn secondary" style={{marginLeft:6}} onClick={()=>setSelected(x.id)}>Fájlok</button>{x.status!=='ARCHIVED'&&<button className="btn danger" style={{marginLeft:6}} onClick={()=>archive(x.id)}>Archiválás</button>}</td></tr>)}</tbody></table></div>
 {selected&&<div className="modal" onClick={()=>setSelected('')}><div className="modalbox" onClick={e=>e.stopPropagation()}><button className="btn secondary" onClick={()=>setSelected('')}>Bezárás</button><MediaManager dogId={selected}/></div></div>}
 </>;
}
